### PR TITLE
Can I add my blog here? 🙏

### PR DESCRIPTION
**Pull request by elbrujohalcon**
Pretty please? 🙏

- [x] I acknowledge my contribution to the website does not assert comparative or superlative differences of one product, project, company, or individual over another.

### CODE REVIEW

**Comment by elbrujohalcon** [comment]
Also… You should consider reviewing http://www.planeterlang.com/ … it's a compilation of erlang/beam-related blogs from around the world.

**Comment by starbelly** [comment]
@elbrujohalcon planeterlang is is in there, we pinged you in the original issue and I was going to reach out to you again, you just read my mind 😁 ❤️

**Review by starbelly — APPROVED** [review]

**Comment by starbelly** [comment]
Thank you @elbrujohalcon ❤️💛💚💙💜

**Comment by elbrujohalcon** [comment]
> @elbrujohalcon planeterlang is is in there, we pinged you in the original issue and I was going to reach out to you again, you just read my mind 😁 ❤️  

I meant to say that you should add some of the blogs in that list directly here.

**Pull request merged**
