### PR TITLE
First approach static_map creation from files

### PR DESCRIPTION
**Pull request by joaquinalcerro**
This is the first approach to create the static map from files. I created a directory under page directory and moved the corresponding files to it. I also created a recursive function to create the map from files.

Looks like it is working and code added can be updated.... just wanted to show the code for comments. When I say working, I ment the creation of the map only and we have to add the "/" => "index.html" to the starting map(state).

Best regards,

### CODE REVIEW

**Comment by starbelly** [comment]
@joaquinalcerro Thank you for your effort.  I'm not sure it's working though. I cloned your branch, compiled etc, but when I tried to hit some of the pages I got template not found errors.
  
  Back story: When I hacked this part together it seemed like a good idea. Someone could simply make a mostly static page and drop it in a directory. 

 I went down a similar path in regards to getting rid of the hard coded table and building up a map based on  but in doing so I realized for nested paths we'll have to figure out what view it should use etc.  Generally I started to find myself making too much of an effort to make something very simple work. Now I'm on the fence 🤔 

  It might be better to revert how things were before https://github.com/erlef/website/commit/d0a18a154cd52a00bd7a5e71630d4ad19a5a8586 and back to traditional routing and controller phoenix idioms. What do you think?

**Comment by joaquinalcerro** [comment]
@starbelly Thanks for your feedback.

Definitely, the code still doesn't work well yet. The idea was to show you my first approach in the sense that, in order to know the correct path, I created a sub-directory that will reflect the internal route to be added.

In my opinion, we should work with the hole phoenix framework even thou it might be an overkill for a static webpage (for the moment) but what we obtain with this approach, is the opportunity to get help from the community that has experience with Phoenix Framework and the onboarding of new volunteers would be fast and easy.

Let me know your thoughts to work this out.

Best regards,

**Comment by starbelly** [comment]
@joaquinalcerro In regards to the above conversation... I think we can close this and it's related issue and circle back. Would you be interested in #2 ?

**Comment by joaquinalcerro** [comment]
Hi @starbelly, I installed the full calendar library yesterday  and I've been looking at the code for a couple of hours. 

Even though the installation was straightforward I wasn't able to quickly understand the library. 

I know if I keep going around the code I will figure it out but it might take time. How much time do we have? Do you know this code? Can you give me a heads up to make it faster?

Best regards,

**Comment by joaquinalcerro** [comment]
Do we need a exact replica of the styling and features or styling can be similar.

From the feature stand point of view, what features should we implement first?

I will wait for your response, 

Best regards.

**Comment by starbelly** [comment]
Just saw this and assume it's in regards to 
https://github.com/erlef/website/issues/5 .

I'd say for the moment close enough is good enough. Originally we wanted 
full parity but PR desmond's PR yesterday, that has changed. In my 
oppinion, I'd say go for what you think looks nice, but don't get 
married to it :)

--

Bryan

**Pull request closed without merging**
