### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
- [x] I acknowledge my contribution to the website does not assert comparative or superlative differences of one product, project, company or individual over another.

# Screenshots

Please attach screenshots and/or gifs of any visible changes to pages here.

### CODE REVIEW

**Review by starbelly — APPROVED** [review]
Love the attention to detail :) ❤️ Thank you!

**Comment by starbelly** [comment]
It looks like there's a test that needs to be updated @kianmeng Could you update that?

**Comment by kianmeng** [comment]
@starbelly Done.

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
