### PR TITLE
Adolfo Neto's phot to be added to the Education, Training, & Adoption…

### PR DESCRIPTION
**Pull request by adolfont**
… Working Group

https://erlef.org/wg/education

### CODE REVIEW

**Comment by starbelly** [comment]
Thank you 😄  Can you add yourself in config https://raw.githubusercontent.com/erlef/website/master/priv/working_groups/education.md ?

**Comment by adolfont** [comment]
I am not sure but I think I have correctly added my name to priv/working_groups/education.md

**Comment by starbelly** [comment]
You have! Merging and deploying ❤️

**Comment by adolfont** [comment]
Thanks!

**Pull request merged**
