### PR TITLE
add layout partials

### PR DESCRIPTION
**Pull request by starbelly**
Hey @ghislaineguerin . This is the start of some partials, I figured we could hash the the details out in this PR. I assume you would like to make partials for the hero(s), svg, etc. but wanted to check first before creating all the things. This PR targets your design-update branch.

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@starbelly this looks great. And yes, I want to make partials for the hero as well. thanks!

**Comment by starbelly** [comment]
@ghislaineguerin Do you think the `<section>` should be part of the partial? I figured it would be more flexible not to. 

Also, we could tackle the bootstrap override problem as part of this PR. I saw the app.css was imported before bootstrap, that could cause some issues. However if you are wanting to say override the primary color and have that be applied to btn-primary, text-primary, etc then we will need to compile bootstrap from source and provide an overrides file using sass or less. Just let me know.

**Comment by ghislaineguerin** [comment]
@starbelly Yes, I need to override primary and other variables. Bootstrap has a variables.scss file for that.
I don't think section should be part of it, agreed.

**Comment by starbelly** [comment]
Sounds good, let me get that in this PR in a bit.

**Comment by starbelly** [comment]
@ghislaineguerin Ok, bootstrap compile from sass and a custom.scss file is in place. As a test I set primary color to hot pink 😁 . I also removed full calendar completely. Still got some partial work to do then this should be good to go I think. Can you try this branch and make sure bootstrap and variables work on your end?

**Comment by starbelly** [comment]
@ghislaineguerin please take a look at the partials now. What I've done for the clip-svg stuff is add two helper functions `right_svg_hero` and `left_svg_hero`. These work better than partials for these cases. The names of these functions are incorrect/bad so if you could tell me what you think these should be called I can adjust. 

At this point, simply let me know what else you need as far as reusable html helpers (like the above) and partials. Otherwise, I'd say merge it!

**Comment by ghislaineguerin** [comment]
@starbelly is it ok to merge with the failing test?

**Comment by starbelly** [comment]
@ghislaineguerin Hmmm the test was already failing, but I can fix up, I need to squash first too.

**Comment by starbelly** [comment]
@ghislaineguerin I squashed and fixed up the test, but before I merge, was there any better name you can think of for those html helpers? Can be renamed later in your PR, but just checking.

**Comment by ghislaineguerin** [comment]
@starbelly I'll rename them later, no worries. Thanks

**Pull request merged**
