### PR TITLE
Update README.md with general and blog post creation instructions

### PR DESCRIPTION
**Pull request by starbelly**

### CODE REVIEW

**Comment by mendeza** [comment]
This appears to be a very helpful addition. Any reason not to merge it?

**Comment by starbelly** [comment]
@mendeza Was waiting for not so much to be in flux and appears to be the case now. I will get this merged at some point today.

**Comment by tomekowal** [comment]
If I may suggest: instead of adding `Prerequisites` section in the readme, it might be better to add `.tool-versions` like in phoenix demo repo:
https://github.com/DockYard/live_view_demo/blob/master/.tool-versions

Then in Readme.md mention asdf version manager https://asdf-vm.com/#/

**Comment by starbelly** [comment]
I wouldn't be opposed to adding a `.tools-version`, however not everyone uses asdf.

**Comment by starbelly** [comment]
@tomekowal Do you think the prereq's section is confusing?

**Comment by tomekowal** [comment]
@starbelly Not at all. Just thought that whatever Elixir/Phoenix team uses should be standard in the community :)

**Comment by starbelly** [comment]
Cool.

**Pull request merged**
