### PR TITLE
standardize working group names

### PR DESCRIPTION
**Pull request by bgmarx**
what do you think about standardizing the WG names?

### CODE REVIEW

**Comment by starbelly** [comment]
I think it's a fine idea. I had this thought over the weekend.  What format/names are you thinking?

**Comment by bgmarx** [comment]
For the moment, just removing `Working Group` from `Marketing Working Group`. I think the rest are fine.

**Comment by starbelly** [comment]
I hear you and agree.

**Comment by starbelly** [comment]
Closing this as it is non-relevant now.

**Pull request closed without merging**
